DROP TABLE users IF EXISTS;
DROP TABLE authorities IF EXISTS;
DROP TABLE user_authorities IF EXISTS;
DROP TABLE authority IF EXISTS;

CREATE TABLE IF NOT EXISTS users (
 	 id 				INTEGER IDENTITY PRIMARY KEY,
 	 firstName 			VARCHAR(60) NOT NULL,  
     lastName 			VARCHAR(60) NOT NULL,
     username 			VARCHAR(60) NOT NULL,  
     password 			VARCHAR(120) NOT NULL,
     email 				VARCHAR(60) NOT NULL
);  

CREATE TABLE IF NOT EXISTS user_authority (
	user_id 			INTEGER NOT NULL,
	authority_id 		INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS authority (
	id 					INTEGER IDENTITY PRIMARY KEY,
	name 				VARCHAR(60) NOT NULL
);

DROP TABLE spot IF EXISTS;
DROP TABLE activity IF EXISTS;
DROP TABLE advertisement IF EXISTS;
DROP TABLE rating IF EXISTS;
DROP TABLE activity IF EXISTS;
DROP TABLE location IF EXISTS;

CREATE TABLE spot(
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    LOCATION_ID INTEGER,
    USER_USERID INTEGER
);

CREATE TABLE rating(
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE activity(
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    RATING_ID INTEGER,
    SPOT_SPOTID INTEGER
);

CREATE TABLE advertisement(
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    SPOT_SPOTID INTEGER,
    USER_ID INTEGER
);